spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_board?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect